In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
sum(L)

51.9464948498363

In [5]:
ba = np.random.rand(10**7)
%timeit sum(ba)
%timeit np.sum(ba)

651 ms ± 2.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.36 ms ± 16.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit min(ba)
%timeit np.min(ba)

591 ms ± 2.27 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.25 ms ± 53.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
M = np.random.random((3,4))
print(M)

[[0.24839095 0.95790639 0.63971718 0.17609589]
 [0.32140831 0.12562523 0.42097655 0.14630655]
 [0.0043173  0.78348929 0.82822537 0.56803736]]


In [8]:
M.sum()

5.220496366523315

In [9]:
M.min(axis=0)

array([0.0043173 , 0.12562523, 0.42097655, 0.14630655])

In [10]:
M.min(axis=1)

array([0.17609589, 0.12562523, 0.0043173 ])