In [1]:
import numpy as np
np.random.seed(0)

def computeReciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
computeReciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [3]:
bigArray = np.random.randint(1, 100, size=1000000)
%timeit computeReciprocals(bigArray)

1.72 s ± 12.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
print(computeReciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [6]:
%timeit (1.0 / bigArray)

1.51 ms ± 13 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [10]:
x = np.arange(9).reshape(3,3)
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [11]:
x = np.arange(4)
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])