In [10]:
import numpy as np
np.__version__

'1.14.3'

In [11]:
np?

In [13]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [14]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [15]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [16]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [17]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [21]:
np.arange(0, 20 ,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.random.random((3,3))

array([[0.742044  , 0.89440512, 0.63693488],
       [0.07082357, 0.57295009, 0.84615679],
       [0.37092297, 0.76482603, 0.08828758]])

In [23]:
np.random.normal(0,1,(3,3))

array([[-1.30592371,  1.50299673, -1.30353704],
       [ 1.22948782,  2.49069494, -1.30899843],
       [-1.17148906, -0.41638779,  1.08539667]])

In [24]:
np.random.randint(0,10,(3,3))

array([[1, 6, 4],
       [2, 5, 4],
       [5, 8, 9]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.empty(3)

array([1., 1., 1.])